version: '3.8'
services:
  card-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./assets/fonts:/app/assets/fonts:ro
    restart: unless-stopped
